# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: CopyFiles@2
  displayName: Copy provisioning scripts
  inputs:
    SourceFolder: acme.product.api.provisioning
    TargetFolder: '$(build.artifactstagingdirectory)/iac'

- task: PublishBuildArtifacts@1
  displayName: Publish infrastructure artifacts
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/iac'
    ArtifactName: iac

# - task: CopyFiles@2
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
